theme: jekyll-theme-cayman
title: lernOS
description: The art of self-directed, lifelong learning.
show_downloads: false
github:
  en_url: https://github.com/simondueckert/lernos/blob/master/lernOS%20Guide/en/lernOS-Guide-en.md
  de_url: https://github.com/simondueckert/lernos/blob/master/lernOS%20Guide/de/lernOS-Guide-de.md
